---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagd
  labels:
    app: flagd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flagd
  template:
    metadata:
      labels:
        app: flagd
    spec:
      containers:
        - name: flagd
          image: ghcr.io/open-feature/flagd:v0.4.2 
          ports:
            - containerPort: 8013 # gRPC port
            - containerPort: 8014 # HTTP port (OFREP)
          args:
            - start
            - --uri
            - file:/etc/flagd/flags.json
            - --debug
          volumeMounts:
            - name: flagd-config-volume
              mountPath: /etc/flagd
      volumes:
        - name: flagd-config-volume
          configMap:
            name: flagd-config
---
apiVersion: v1
kind: Service
metadata:
  name: flagd
  labels:
    app: flagd
spec:
  selector:
    app: flagd
  ports:
    - name: grpc
      protocol: TCP
      port: 8013
      targetPort: 8013
    - name: http
      protocol: TCP
      port: 8014
      targetPort: 8014
  type: ClusterIP # Use LoadBalancer for external access if needed
