---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flagd-config
  labels:
    app: flagd
data:
  flags.json: |
    {
      "flags": {
        "my-new-feature": {
          "state": "ENABLED",
          "variants": {
            "on": true,
            "off": false
          },
          "defaultVariant": "off"
        },
        "another-feature": {
          "state": "ENABLED",
          "variants": {
            "red": "#FF0000",
            "blue": "#0000FF"
          },
          "defaultVariant": "blue"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagd
  labels:
    app: flagd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flagd
  template:
    metadata:
      labels:
        app: flagd
    spec:
      containers:
        - name: flagd
          image: ghcr.io/open-feature/flagd:latest # Use a specific version in production
          ports:
            - containerPort: 8013 # gRPC port
            - containerPort: 8014 # HTTP port (OFREP)
          command: ["flagd", "start"]
          args:
            - "--uri=file:/etc/flagd/flags.json" # Mount ConfigMap as a file source
            - "--sync-refresh-interval=5s" # Refresh flags every 5 seconds
          volumeMounts:
            - name: flagd-config-volume
              mountPath: /etc/flagd
      volumes:
        - name: flagd-config-volume
          configMap:
            name: flagd-config
---
apiVersion: v1
kind: Service
metadata:
  name: flagd
  labels:
    app: flagd
spec:
  selector:
    app: flagd
  ports:
    - name: grpc
      protocol: TCP
      port: 8013
      targetPort: 8013
    - name: http
      protocol: TCP
      port: 8014
      targetPort: 8014
  type: ClusterIP # Use LoadBalancer for external access if needed
